import type { NextPage } from "next"
import Head from "next/head"
import axios from "axios"
import { Video } from "../types"
import VideoCard from "../components/VideoCard"
import NoResult from "../components/NoResult"

interface Iprops {
  videos: Video[]
}

const Home = ({ videos }: Iprops) => {
  console.log(videos)

  return (
    <div>
      <Head>
        <title>TikTok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex flex-col gap-10 videos h-full">
          {videos.length ? (
            videos.map((video: Video) => (
              <VideoCard post={video} key={video._id} />
            ))
          ) : (
            <NoResult text={"No videos"} />
          )}
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const { data } = await axios.get(`http://localhost:3000/api/post`)

  return {
    props: {
      videos: data,
    },
  }
}

export default Home
