import type { NextPage } from "next"
import Head from "next/head"
import axios from "axios"

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>TikTok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-4xl">Discover TikTok</h1>
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const response = await axios.get(`http://localhost:3000/api/post`)

  console.log(response.data.name)

  return {
    props: {},
  }
}

export default Home
